#!/bin/bash

mv [[:upper:]]* /tmp/u
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation && echo OK || echo FAILURE
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation/tree/main && echo OK || echo FAILURE
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation/tree/main/module1_task0 && echo OK || echo FAILURE
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation/tree/main/module1_task0/ && echo OK || echo FAILURE
#test -x ./3-lets_move && echo OK || echo FAILURE




