#!/bin/bash

ls -la
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation && echo OK || echo FAILURE
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation/tree/main && echo OK || echo FAILURE
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation/tree/main/module0_task2 && echo OK || echo FAILURE
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation/tree/main/module0_task2/2-listmorefiles && echo OK || echo FAILURE
#test -x ./2-listmorefiles && echo OK || echo FAILURE




