#!/bin/bash

touch hello
chmod u+rwx,g+rx,o+r hello
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation && echo OK || echo FAILURE
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation/tree/main && echo OK || echo FAILURE
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation/tree/main/module0_task4 && echo OK || echo FAILURE
#curl --silent --fail --output /dev/null https://github.com/Analogic84/validation/tree/main/module0_task4/4-multiple_permissions && echo OK || echo FAILURE
#test -x ./4-multiple_permissions && echo OK || echo FAILURE




